import { Inter } from "next/font/google";
import "./globals.css";
import { io, Socket } from 'socket.io-client'
import { UserContextProvider } from '@/context/UserContext';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </head>
      <UserContextProvider>

        <body className={inter.className}>{children}</body>
      </UserContextProvider>
    </html>
  );
}
